In [377]:
import math
import numpy as np
from numpy import linalg as LA

A = np.array([np.array([-5.93188,1.68187,-2.56264,3.82366,5.37339]),
             np.array([1.68187,3.59172,-4.63607,5.67858,-6.89993]),
            np.array([-2.56264,-4.63607,-0.0515765,9.43968,8.7402]),
             np.array([3.82366,5.67858,9.43968,3.87127,0.307322]),
             np.array([5.37339,-6.89993,8.7402,0.307322,-7.27348])])

A1=np.array([np.array([-5.93188,1.68187,-2.56264,3.82366,5.37339]),
             np.array([1.68187,3.59172,-4.63607,5.67858,-6.89993]),
            np.array([-2.56264,-4.63607,-0.0515765,9.43968,8.7402]),
             np.array([3.82366,5.67858,9.43968,3.87127,0.307322]),
             np.array([5.37339,-6.89993,8.7402,0.307322,-7.27348])])
H= np.array([np.array([1.0,0,0,0,0]),
             np.array([0.0,1,0,0,0]),
            np.array([0.0,0,1,0,0]),
             np.array([0.0,0,0,1,0]),
             np.array([0.0,0,0,0,1])])
Vk=np.array([np.array([1.0,0,0,0,0]),
             np.array([0.0,1,0,0,0]),
            np.array([0.0,0,1,0,0]),
             np.array([0.0,0,0,1,0]),
             np.array([0.0,0,0,0,1])])
N=5
eps=0.00001
k=0
max=-900000
ind_i=0
ind_j=0                
count=0  
for i in range(N):
        for j in range(N):
            if(j>i):
                if(abs(A[i][j])>=max):
                    max=abs(A[i][j])
                    ind_i=i
                    #строка
                    ind_j=j

while(max>eps): 
    #составляем H
    for i in range(N):
        for j in range(N):
            if(i==j):
                H[i][j]=1
            else:
                H[i][j]=0
    Pk=2*A[ind_i][ind_j]/(A[ind_i][ind_i]-A[ind_j][ind_j])
    fi=0.5*(np.arctan(Pk))
    #sin=np.sign(Pk)*math.sqrt(0.5*(1-1/math.sqrt(1+Pk*Pk)))
    #cos=math.sqrt(0.5*(1+1/math.sqrt(1+Pk*Pk)))
    #H[ind_i][ind_i]=cos
    #H[ind_i][ind_j]=-sin
    #H[ind_j][ind_i]=sin
    #H[ind_j][ind_j]=cos
    H[ind_i,ind_i]=np.cos(fi)
    H[ind_i,ind_j]=-np.sin(fi)
    H[ind_j,ind_i]=np.sin(fi)
    H[ind_j,ind_j]=np.cos(fi)
    #print(H)
    #вычисляем A
    H_T=H.T
    A=np.dot(H_T,A)
    A=np.dot(A,H)
    #до этого места нахождение H,A,H^-1
    max=0
    count+=1
    for i in range(0,N):
        for j in range(0,N):
            if(j>i):
                if(abs(A[i][j])>=max):
                    max=abs(A[i][j])
                    ind_i=i
                    #строка
                    ind_j=j
                    #столбец
    #матрица собственных значений
    lambda_matrix = np.diag(A)
    #матрица собственных векторов
    Vk=Vk.dot(H)
    #print(sum)


print("число итераций",count)
print("Матрица собственнных векторов")
print(Vk)
print("Max_element in A",max)
print("Матрица A")
print(A)
print("Собственнные числа")
print(lambda_matrix)
#A1 = np.matrix('2 1;1 3')
print("Матрица A0")
print(A1)
print(Vk[:,0])
print(A1.dot(Vk[:,0]))
print(Vk[:,0].dot(A[0][0]))
D=np.matrix('-2.701 11.027 -9.661 0.1035 -0.48')
X=np.matrix('-0.859 -0.007526 -0.328 -0.0398 0.39')
X1=np.matrix('-0.859078 0.13168 -0.055851 0.103527 -0.480425')
#print(X.transpose())
#print(A1.dot(X.transpose()))
#print(X.transpose()*D[0,0])


число итераций 28
Матрица собственнных векторов
[[ 0.85908  0.13168 -0.05585  0.10353 -0.48043]
 [-0.00753  0.75465  0.60137 -0.25308  0.06893]
 [-0.32845 -0.05613  0.41141  0.68287 -0.50338]
 [-0.0398   0.58388 -0.53323  0.54843  0.26904]
 [ 0.39047 -0.26287  0.42619  0.39767  0.66232]]
Max_element in A 7.800372066702937e-06
Матрица A
[[ -2.70169  -0.        0.        0.        0.     ]
 [ -0.       11.0271   -0.       -0.       -0.     ]
 [  0.       -0.       -9.66117   0.        0.     ]
 [  0.       -0.        0.       13.94914   0.00001]
 [  0.       -0.        0.        0.00001 -18.40733]]
Собственнные числа
[ -2.70169  11.0271   -9.66117  13.94914 -18.40733]
Матрица A0
[[-5.93188  1.68187 -2.56264  3.82366  5.37339]
 [ 1.68187  3.59172 -4.63607  5.67858 -6.89993]
 [-2.56264 -4.63607 -0.05158  9.43968  8.7402 ]
 [ 3.82366  5.67858  9.43968  3.87127  0.30732]
 [ 5.37339 -6.89993  8.7402   0.30732 -7.27348]]
[ 0.85908 -0.00753 -0.32845 -0.0398   0.39047]
[-2.32096  0.02033  0.8873